source 'http://rubygems.org'

gem 'sinatra'
gem 'dalli'
gem 'shotgun'
gem 'json'
gem 'rest-client'
gem 'sqlite3'
gem 'mongo'
gem 'bson_ext'
gem 'mustache'
gem 'capistrano'
gem 'unicorn'
gem 'resque'
gem 'mixpanel'
gem 'resque-cleaner'
gem 'resque-history'
gem 'useragent'